CREATE TABLE AMERICA(
	VEHICLE_ID		INT(6),
	VEHICLETYPE_ID	INT(6),
	VEHICLE_NAME	char(36),
	LINETYPE_ID		INT(6),
	TIER			char(3),
	RP_COST			INT(10),
	LION_COST		INT(10),
	IMAGE_FILE_NAME	char(36),
	PRIMARY KEY(VEHICLE_ID)
);

CREATE TABLE GERMANY(
	VEHICLE_ID		INT(6) ,
	VEHICLETYPE_ID	INT(6),
	VEHICLE_NAME	char(36),
	LINETYPE_ID		INT(6),
	TIER			char(3),
	RP_COST			INT(10),
	LION_COST		INT(10),
	IMAGE_FILE_NAME	char(36),
	PRIMARY KEY(VEHICLE_ID)
);

CREATE TABLE UNITED_KINGDOM(
	VEHICLE_ID		INT(6),
	VEHICLETYPE_ID	INT(6),
	VEHICLE_NAME	char(36),
	LINETYPE_ID		INT(6),
	TIER			char(3),
	RP_COST			INT(10),
	LION_COST		INT(10),
	IMAGE_FILE_NAME	char(36),
	PRIMARY KEY(VEHICLE_ID)
);

CREATE TABLE RUSSIAN(
	VEHICLE_ID		INT(6),
	VEHICLETYPE_ID	INT(6),
	VEHICLE_NAME	char(36),
	LINETYPE_ID		INT(6),
	TIER			char(3),
	RP_COST			INT(10),
	LION_COST		INT(10),
	IMAGE_FILE_NAME	char(36),
	PRIMARY KEY(VEHICLE_ID)
);

CREATE TABLE JAPAN(
	VEHICLE_ID		INT(6),
	VEHICLETYPE_ID	INT(6),
	VEHICLE_NAME	char(36),
	LINETYPE_ID		INT(6),
	TIER			char(3),
	RP_COST			INT(10),
	LION_COST		INT(10),
	IMAGE_FILE_NAME	char(36),
	PRIMARY KEY(VEHICLE_ID)
);

CREATE TABLE CHINA(
	VEHICLE_ID		INT(6),
	VEHICLETYPE_ID	INT(6),
	VEHICLE_NAME	char(36),
	LINETYPE_ID		INT(6),
	TIER			char(3),
	RP_COST			INT(10),
	LION_COST		INT(10),
	IMAGE_FILE_NAME	char(36),
	PRIMARY KEY(VEHICLE_ID)
);

CREATE TABLE ITALY(
	VEHICLE_ID		INT(6),
	VEHICLETYPE_ID	INT(6),
	VEHICLE_NAME	char(36),
	LINETYPE_ID		INT(6),
	TIER			char(3),
	RP_COST			INT(10),
	LION_COST		INT(10),
	IMAGE_FILE_NAME	char(36),
	PRIMARY KEY(VEHICLE_ID)
);

CREATE TABLE SWEDEN(
	VEHICLE_ID		INT(6),
	VEHICLETYPE_ID	INT(6),
	VEHICLE_NAME	char(36),
	LINETYPE_ID		INT(6),
	TIER			char(3),
	RP_COST			INT(10),
	LION_COST		INT(10),
	IMAGE_FILE_NAME	char(36),
	PRIMARY KEY(VEHICLE_ID)
);

CREATE TABLE FRANCE(
	VEHICLE_ID		INT(6),
	VEHICLETYPE_ID	INT(6),
	VEHICLE_NAME	char(36),
	LINETYPE_ID		INT(6),
	TIER			char(3),
	RP_COST			INT(10),
	LION_COST		INT(10),
	IMAGE_FILE_NAME	char(36),
	PRIMARY KEY(VEHICLE_ID)
);

